### ISSUE TITLE
Creating new job results in exception ...

### ISSUE THREAD

**Issue by DeepDiver1975** [groupon/DotCi#101]
````
A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.
Stack trace

javax.servlet.ServletException: java.lang.ClassCastException: hudson.util.CopyOnWriteList cannot be cast to hudson.model.JobProperty
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:391)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: hudson.util.CopyOnWriteList cannot be cast to hudson.model.JobProperty
	at hudson.model.Job.onLoad(Job.java:217)
	at hudson.model.AbstractProject.onLoad(AbstractProject.java:318)
	at hudson.model.Project.onLoad(Project.java:95)
	at com.groupon.jenkins.dynamic.build.DbBackedProject.onLoad(DbBackedProject.java:89)
	at com.groupon.jenkins.dynamic.build.DynamicProject.onLoad(DynamicProject.java:106)
	at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.getJobsForThisContainer(OrganizationContainer.java:138)
	at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.init(OrganizationContainer.java:129)
	at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.<init>(OrganizationContainer.java:87)
	at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer$DescriptorImpl.newInstance(OrganizationContainer.java:221)
	at hudson.model.ItemGroupMixIn.createProject(ItemGroupMixIn.java:283)
	at jenkins.model.Jenkins.createProject(Jenkins.java:2483)
	at jenkins.model.Jenkins.createProject(Jenkins.java:2479)
	at jenkins.model.Jenkins.createProject(Jenkins.java:2514)
	at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainerRepository.getOrCreateContainer(OrganizationContainerRepository.java:34)
	at com.groupon.jenkins.dynamic.build.repository.DynamicProjectRepository.createNewProject(DynamicProjectRepository.java:141)
	at com.groupon.jenkins.buildsetup.GithubReposController.doCreateProject(GithubReposController.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 64 more

**Comment by Dinoshauer** [comment]
I'm getting this one on a newly installed Jenkins v1.580.3, however v1.580.2 doesn't raise this.

    Feb 06, 2015 9:27:02 AM org.eclipse.jetty.util.log.JavaUtilLog warn
    WARNING: Error while serving http://<my-ip>/mygithubprojects/NewDotCiJobRepoAction/createProject
    java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
        at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:371)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
        at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:391)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:648)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:237)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.groupon.jenkins.buildsetup.GithubReposController.doDynamic(GithubReposController.java:96)
        ... 69 more
    Caused by: java.lang.NoSuchMethodError: hudson.plugins.build_timeout.BuildTimeoutWrapper.<init>(IZZIILjava/lang/String;)V
        at com.groupon.jenkins.dotci.listeners.DotCiProjectSetupListener.onCreated(DotCiProjectSetupListener.java:44)
        at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:185)
        at hudson.model.listeners.ItemListener$2.apply(ItemListener.java:183)
        at hudson.model.listeners.ItemListener.forAll(ItemListener.java:166)
        at hudson.model.listeners.ItemListener.fireOnCreated(ItemListener.java:183)
        at hudson.model.ItemGroupMixIn.createProject(ItemGroupMixIn.java:294)
        at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.createProject(OrganizationContainer.java:246)
        at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.createProject(OrganizationContainer.java:242)
        at com.groupon.jenkins.dynamic.organizationcontainer.OrganizationContainer.createProject(OrganizationContainer.java:238)
        at com.groupon.jenkins.dynamic.build.repository.DynamicProjectRepository.createNewProject(DynamicProjectRepository.java:145)
        at com.groupon.jenkins.buildsetup.NewDotCiJobRepoAction.doCreateProject(NewDotCiJobRepoAction.java:39)
        ... 74 more

Here's output from MongoDB:

    > db.job.find({containerName: "FalconSocial"});
    {
        "_id": ObjectId ("54d488e660b2abb898ee4ff7"),
        "className": "com.groupon.jenkins.dynamic.build.DynamicProject",
        "name": "Listen-dotCI",
        "containerName": "FalconSocial",
        "builders": [
        ],
        "publishers": [
        ],
        "buildWrappers": [
        ],
        "scm": {
            "className": "hudson.scm.NullSCM"
        },
        "canRoam": false ,
        "disabled": false ,
        "blockBuildWhenDownstreamBuilding": false ,
        "blockBuildWhenUpstreamBuilding": false ,
        "triggers": [
        ],
        "concurrentBuild": false ,
        "keepDependencies": false ,
        "properties": [
        ]
    }

**Comment by gblikegroupon** [comment]
@Dinoshauer This seems to be a different issue than what DeepDiver1975 reported. What version of the built timeout plugin are you using? https://github.com/jenkinsci/build-timeout-plugin.

**Comment by Dinoshauer** [comment]
@gblikegroupon The build timeout plugin is v1.14.1 - It's the one that was installed with the dotci-plugins-plugin

**Comment by gblikegroupon** [comment]
@Dinoshauer I've updated the DotCi-Plugins-Starter-Pack to use version 1.14 of the build-timeout-plugin. It should work on the next release.

**Comment by Dinoshauer** [comment]
I think I actually tried that already by manually downgrading to 1.14, but
let's see :)

**Comment by wesgurn** [comment]
Any update on this issue?  I am seeing it as well on Jenkins 1.599.  I tried downgrading to build-timeout-plugin 1.14 and I get the same error.

**Comment by wesgurn** [comment]
Just an update uninstalling the DotCI-Plugins-Starter-Pack, downgrading to Jenkins 1.596, and resetting the MongoDB database fixed the issue.

My guess is something between Jenkins 1.596 and Jenkins 1.599 is breaking it.  Not sure if its related to the Plugin Starter pack as well.

**Comment by prabugp** [comment]
Recording my experience: On Jenkins 1.592, had the same issue as @DeepDiver1975 . I had the Dot Ci Plugins starter pack 1.1.1 installed. I stumbled across #66 and uninstalling the starter pack and re-installing it again removed the error for me. This could be one thing to try out if someone faces this issue.
