### ISSUE TITLE
DockerBuild fails

### ISSUE THREAD

**Issue by marcellodesales** [groupon/DotCi#138]
Hi there,

First of all, thanks for providing this as Open-source... 

Setup
-----

* docker.corp.intuit.net: runs all the DotCi dependencies (Jenkins + Slaves + Mongo)

![screen shot 2015-06-24 at 4 45 18 pm](https://cloud.githubusercontent.com/assets/131457/8344022/99fdfb44-1a90-11e5-914b-e4aa4014f530.png)

* github.intuit.net: GitHub enterprise server

Execution
------

The regular "New DotCi build properly loads all my organizations, and I can successfully create a new Build... 

When clicking on the button "Build with Parameter", the build fails to do a "git pull"...  
It looks like the build cannot create the Git repo because it is using the suffix of the GitHub Enterprise API path `/api/v3`, apparently from the `Github Api Url` instead of the `Github Web Url` on the Git URL at `git remote add origin git@github.intuit.com/api/v3/repos:mdesales/isp.git`... Is that the correct notation when using the repos API?

![screen shot 2015-06-24 at 4 53 26 pm](https://cloud.githubusercontent.com/assets/131457/8344112/9b6f621e-1a91-11e5-9304-efccbaad91d3.png)

```
Started by user anonymous
Started by: null
Building remotely on ce865bf518ef (swarm) in workspace /var/jenkins_home/worker/workspace/mdesales/isp
[isp] $ /bin/bash -le /tmp/hudson8603557114623679067.sh
$  chmod -R u+w . ; find . ! -path "./deploykey_rsa.pub" ! -path "./deploykey_rsa" -delete
$  git init
Initialized empty Git repository in /var/jenkins_home/worker/workspace/mdesales/isp/.git/
$  git remote add origin git@github.intuit.com/api/v3/repos:mdesales/isp.git
$  git fetch origin master
fatal: 'git@github.intuit.com/api/v3/repos:mdesales/isp.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Build step 'Execute shell' marked build as failure
setting commit status on Github for http://github.intuit.com/api/v3/repos/mdesales/isp/commit/3297d5c6e1d98692370150ed626691cc7eeb77ba
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

Please help!

Thanks a lot for any help!

**Comment by marcellodesales** [comment]
Also, I was looking at the Mongodb collections and I noticed that the GitHub URLs are stored with the protocol "http" instead of "https"... Does it represent a potential problem?

```js
[root@pppdc9prd8ok mdesales]# docker run -it --link mongodb-dotci:mongo --rm mongo sh -c 'exec mongo "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/dotci"'
MongoDB shell version: 3.0.4
connecting to: 172.17.0.7:27017/dotci
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
Server has startup warnings: 
2015-06-23T22:37:21.774+0000 I STORAGE  [initandlisten] 
2015-06-23T22:37:21.775+0000 I STORAGE  [initandlisten] ** WARNING: Readahead for /data/db is set to 4096KB
2015-06-23T22:37:21.775+0000 I STORAGE  [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
2015-06-23T22:37:21.775+0000 I STORAGE  [initandlisten] **          http://dochub.mongodb.org/core/readahead
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] 
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] 
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-06-23T22:37:22.086+0000 I CONTROL  [initandlisten] 
> db
dotci
> db.getCollectionNames();
[ "github_tokens", "job", "run", "system.indexes" ]
> db.github_tokens.find();
{ "_id" : ObjectId("5589e923e4b0c503dd544132"), "user" : "mdesales", "access_token" : "r8lO49QxnGrJdB3lVnbdwjoVIE/E1wGJVuhf9Zk/LXIVQSc/in9K7irUiCxKmKVO999iSzwI3BFWMZ3B/PqZjg==", "repo_url" : "http://github.intuit.com/api/v3/repos/servicesplatform-node/isp" }
{ "_id" : ObjectId("558b3f26e4b0b2b8664cbb97"), "user" : "mdesales", "access_token" : "r8lO49QxnGrJdB3lVnbdwjoVIE/E1wGJVuhf9Zk/LXIVQSc/in9K7irUiCxKmKVO999iSzwI3BFWMZ3B/PqZjg==", "repo_url" : "http://github.intuit.com/api/v3/repos/mdesales/isp" }
{ "_id" : ObjectId("558c2e8fe4b0b2b8664cbb9f"), "user" : "kalkadi", "access_token" : "EpddsZwOq82s8ZEoBJsiVOOIpzUBCu00/2Xv/lk/mN4EteJQMtgb3/WVo
```

**Comment by suryagaddipati** [comment]
@marcellodesales thanks for the bug report. Looks like its using the api url for clone (which is obviously wrong) . Let me investigate this.

**Comment by suryagaddipati** [comment]
@marcellodesales seems like what your have observed with regards to `http` vs `https` is the cause of this issue.

**Comment by marcellodesales** [comment]
@suryagaddipati Thanks for looking into it!!! 

I was thinking about an improvement on the approach... Since the GitHub user grants the Jenkins server access to his/her account, the DotCI plugin could create and submit a new SSH key to the repo/organization... With that, it is guaranteed that you will be able to clone with the `git+ssh://` protocol... We are using this strategy on a Docker Hub solution to do Docker images builds based on Git Commits... 

Anyway, please let me know when you get a chance with the fix... Let me know if you need any more information from our setup...

thanks a lot!

**Comment by suryagaddipati** [comment]
I figured out what is going on. There was breaking change in github api. Fix should be out in  a day or two.

**Comment by cbuehler** [comment]
Is there a workaround in the meanwhile?

**Comment by suryagaddipati** [comment]
Fixed in (2.10.0)[http://maven.jenkins-ci.org:8081/content/repositories/releases/com/groupon/jenkins-ci/plugins/DotCi/2.10.0/ ]

**Comment by marcellodesales** [comment]
@suryagaddipati Thanks a lot for this!!! I will verify in our environment!

**Comment by marcellodesales** [comment]
@suryagaddipati I cannot add a new project after the upgrade :( 

1. Added I added .ci.yml, docker-compose.yml, Dockerfile :( to a brand new fork of a repo
------

And I also selected the repo from the new UI (not sure if I like the new UI)...

<img width="1384" alt="screen shot 2015-07-10 at 1 12 21 am" src="https://cloud.githubusercontent.com/assets/131457/8614980/bc9642fa-26a3-11e5-848a-f8374aaaa5f7.png">

2. The following exception shows right after selecting a given repository... 
---------

The follow error shows when I click in the new project of a new repository that 

<img width="1420" alt="screen shot 2015-07-10 at 1 11 13 am" src="https://cloud.githubusercontent.com/assets/131457/8615009/fef07968-26a3-11e5-8bf4-26f612dc145e.png">

And the exception has to do with the implementation... Not sure why...

```
Caused by: java.lang.NoSuchMethodError: org.kohsuke.github.GHRepository.getHtmlUrl()Ljava/net/URL;
```

The full stack is below... Do you think this is a classloader issue?

```java
 Oops!

A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

Stack trace

javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:391)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.plugins.scm_sync_configuration.extensions.ScmSyncConfigurationFilter$1.call(ScmSyncConfigurationFilter.java:46)
	at hudson.plugins.scm_sync_configuration.ScmSyncConfigurationDataProvider.provideRequestDuring(ScmSyncConfigurationDataProvider.java:103)
	at hudson.plugins.scm_sync_configuration.extensions.ScmSyncConfigurationFilter.doFilter(ScmSyncConfigurationFilter.java:42)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:99)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.groupon.jenkins.buildsetup.GithubReposController.doDynamic(GithubReposController.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:371)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 58 more
Caused by: java.lang.NoSuchMethodError: org.kohsuke.github.GHRepository.getHtmlUrl()Ljava/net/URL;
	at com.groupon.jenkins.github.services.GithubRepositoryService.addHook(GithubRepositoryService.java:90)
	at com.groupon.jenkins.github.services.GithubRepositoryService.linkProjectToCi(GithubRepositoryService.java:171)
	at com.groupon.jenkins.dynamic.build.repository.DynamicProjectRepository.createNewProject(DynamicProjectRepository.java:141)
	at com.groupon.jenkins.buildsetup.NewDotCiJobRepoAction.doCreateProject(NewDotCiJobRepoAction.java:39)
	... 72 more
```

**Comment by suryagaddipati** [comment]
@marcellodesales you need to update `github-api` plugin to use latest version of `github-api`. 

Also, Jenkins version needs to be `>1.6*`

``dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>github-api</artifactId>
            <version>1.68</version>
        </dependency>``

**Comment by marcellodesales** [comment]
@suryagaddipati Thanks for checking it... I need to rebuild my jenkins Docker with the latest :( and also upgrade the plugin... I will get back to you during the weekend!

**Comment by marcellodesales** [comment]
@suryagaddipati Resolved!!! Thanks a lot! And I have to say I love the new UI!!!!  My favorite Jenkins UI remake so far!

<img width="1424" alt="screen shot 2015-07-11 at 10 16 23 am" src="https://cloud.githubusercontent.com/assets/131457/8634658/64254c1a-27b6-11e5-800f-78785120804f.png">

But will continue another bug in another thread!
