### ISSUE TITLE
DotCi plugin extension for html publisher appears to be hardcoded

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#169]
My docker-compose.yml has smtp setup as host:mailman port:25 per https://github.com/DotCi/jenkinsci-dotci-example

and this works great where I'm able to test sending email via http://xxx.ngrok.io/configure

But clearly http://xxx.ngrok.io/job/vvitayau/job/docker-sshd/9 failed due to extension per
```
ERROR: Could not send email as a part of the post-build publishers.

javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.ConnectException: Connection refused
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at com.groupon.jenkins.notifications.EmailNotifierBase.sendMail(EmailNotifierBase.java:85)
	at com.groupon.jenkins.notifications.EmailNotifierBase.notify(EmailNotifierBase.java:67)
	at com.groupon.jenkins.notifications.PostBuildNotifier.perform(PostBuildNotifier.java:52)
	at com.groupon.jenkins.buildtype.install_packages.InstallPackagesBuild.runNotifiers(InstallPackagesBuild.java:92)
	at com.groupon.jenkins.buildtype.install_packages.InstallPackagesBuild.runBuild(InstallPackagesBuild.java:83)
	at com.groupon.jenkins.dynamic.build.DynamicBuild$DynamicRunExecution.doRun(DynamicBuild.java:211)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at com.groupon.jenkins.dynamic.build.DynamicBuild.run(DynamicBuild.java:96)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)

Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:288)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	... 17 more

Some error occured trying to send the email...check the Jenkins log

setting commit status on Github for https://api.github.com/repos/vvitayau/docker-sshd/commit/c2d55232693f511ad2937e8a3b4d8710747aaf5c

Finished: FAILURE
```

**Comment by vvitayau** [comment]
The code is not respecting https://github.com/DotCi/jenkinsci-dotci-example/blob/master/configure-dotci.groovy#L39

issue appears to be https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/notifications/EmailNotifierBase.java using

```
import javax.mail.Transport;
 ...
 Transport.send(msg);
```

So going to instead use https://docs.oracle.com/javaee/6/api/javax/mail/Transport.html#send%28javax.mail.Message,%20javax.mail.Address[]%29
```
Transport.send(Message msg, Address[] addresses)
```
