### ISSUE TITLE
Mongo exception when persisting job status

### ISSUE THREAD

**Issue by aheuermann** [groupon/DotCi#205]
We are using the S3 Plugin to publish jars post-build to S3. We get the following error in our jenkins log.  I'm assuming some mongo keys need to be escaped?

```
com.mongodb.WriteConcernException: { "serverUsed" : "localhost/127.0.0.1:27017" , "connectionId" : 970 , "err" : "The dotted field 'jobs-assembly-0.1.0.jar' in 'actions.10.record.jobs-assembly-0.1.0.jar' is not valid for storage." , "code" : 57 , "n" : 0 , "ok" : 1.0}
        at com.mongodb.CommandResult.getException(CommandResult.java:77)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:110)
        at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:102)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:142)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:115)
        at com.mongodb.DBApiLayer$MyCollection.update(DBApiLayer.java:327)
        at com.mongodb.DBCollection.update(DBCollection.java:178)
        at com.mongodb.DBCollection.save(DBCollection.java:818)
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:986)
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1055)
        at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1042)
        at com.groupon.jenkins.dynamic.build.repository.DynamicBuildRepository.save(DynamicBuildRepository.java:48)
        at com.groupon.jenkins.dynamic.build.DbBackedBuild.save(DbBackedBuild.java:128)
        at com.groupon.jenkins.dynamic.build.DbBackedBuild.onEndBuilding(DbBackedBuild.java:139)
        at hudson.model.Run.execute(Run.java:1812)
        at com.groupon.jenkins.dynamic.build.DynamicBuild.run(DynamicBuild.java:99)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:381)
```
Note: This is not specified as a plugin in the `.ci.yml` but rather in the jenkins config itself. Does that affect anything?

**Comment by gblikegroupon** [comment]
There is a mechanism for escaping those keys. It hasn't been well developed, but I happen to be working on it right now.

**Comment by aheuermann** [comment]
@gblikegroupon awesome, thanks for the quick response!
