### ISSUE TITLE
hudson/widgets/BuildHistoryWidget/entries.jelly failures for DotCi as-of jenkins-1.633

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#212]
Jenkins needs to be upgrade for the following security fixes
 * as-of 1.638 - https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-11-11
 * as-of 1.641 - https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-12-09

I suspect the real roadblock is https://github.com/groupon/DotCi-Plugins-Starter-Pack/issues/9 based on the exceptions below.

I've confirmed that [DotCi-2.26.0](https://github.com/groupon/DotCi/tree/DotCi-2.26.0) and [DotCi-Plugins-Starter-Pack-1.6.0](https://github.com/groupon/DotCi-Plugins-Starter-Pack/commits/DotCi-Plugins-Starter-Pack-1.6.0) fails using java 1.8.0_66 and Jenkins 1.637. Invocation of a new dotci build __WORKS__ fine if I rollback to jenkins version 1.628.

```
master_1  | Dec 29, 2015 10:37:50 AM org.eclipse.jetty.util.log.JavaUtilLog warn
master_1  | WARNING: Error while serving http://aeec76ad.ngrok.io/job/victorv/job/jenkinsci-dotci-example/build
master_1  | java.lang.reflect.InvocationTargetException
master_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
master_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
master_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
master_1  | 	at java.lang.reflect.Method.invoke(Method.java:497)
master_1  | 	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
master_1  | 	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
master_1  | 	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
master_1  | 	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
master_1  | 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
master_1  | 	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
master_1  | 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:813)
master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
master_1  | 	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
master_1  | 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
master_1  | 	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
master_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
master_1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
master_1  | 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
master_1  | 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
master_1  | 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
master_1  | 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
master_1  | 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
master_1  | 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
master_1  | 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
master_1  | 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
master_1  | 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
master_1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
master_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
master_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
master_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
master_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
master_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
master_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
master_1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
master_1  | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
master_1  | 	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
master_1  | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
master_1  | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
master_1  | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
master_1  | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
master_1  | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
master_1  | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
master_1  | 	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
master_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
master_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
master_1  | 	at java.lang.Thread.run(Thread.java:745)
master_1  | Caused by: javax.servlet.ServletException: org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-1.643.jar!/hudson/widgets/BuildHistoryWidget/entries.jelly:31:38: <st:include> java.lang.StackOverflowError
master_1  | 	at org.kohsuke.stapler.jelly.JellyRequestDispatcher.forward(JellyRequestDispatcher.java:60)
master_1  | 	at jenkins.model.ParameterizedJobMixIn.doBuild(ParameterizedJobMixIn.java:184)
master_1  | 	at hudson.model.AbstractProject.doBuild(AbstractProject.java:1752)
master_1  | 	... 79 more
master_1  | Caused by: org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-1.643.jar!/hudson/widgets/BuildHistoryWidget/entries.jelly:31:38: <st:include> java.lang.StackOverflowError
master_1  | 	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:745)
master_1  | 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:289)
master_1  | 	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
master_1  | 	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
master_1  | 	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
master_1  | 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
... repeat the last four line above a lot more times
master_1  | Caused by: java.lang.StackOverflowError
master_1  | 	at org.apache.commons.jelly.JellyContext.getVariableWithDefaultValue(JellyContext.java:254)
... then repeat only the last line above 655 more times
```

**Comment by vvitayau** [comment]
Going to retry using DotCi-2.27.0 and DotCi-Plugins-Starter-Pack-1.7.0 if issue goes away.

**Comment by vvitayau** [comment]
Still encountering same issue.

Going to test  out [my rebase of DotCi-Plugins-Starter-Pack](https://github.com/vvitayau/DotCi-Plugins-Starter-Pack/commits/patch-2) and may pilot rebase DotCi from 1.618=>1.641 as well

**Comment by vvitayau** [comment]
Not sure if related but DotCi has __<?jelly escape-by-default='false'?>__ for the following files
/code
./src/main/resources/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
./target/checkout/src/main/resources/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
./target/checkout/target/classes/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
./target/checkout/target/generated-classes/cobertura/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
./target/classes/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
./target/generated-classes/cobertura/com/groupon/jenkins/buildsetup/GithubReposController/repo_actions.jelly
```

**Comment by vvitayau** [comment]
Trying to better isolate where the issue is, i'm no longer using DotCi-Plugins-Starter-Pack

Now experiment with just my DotCi plugin where
```
      <parent>
         <groupId>org.jenkins-ci.plugins</groupId>
         <artifactId>plugin</artifactId>
-        <version>1.618</version>
+        <version>1.641</version>
     </parent>
```

with jenkins-1.643 on docker with the following plugins
```
git-client:1.9.1
git:2.2.2
github-api:1.69
github-oauth:0.22.2
matrix-project:1.2
rebuild:1.25
scm-api:0.2
token-macro:1.10
```

**Comment by vvitayau** [comment]
OK ... still an issue after upgrading various plugins above to the latest. So this is definitely a DotCi issue related to jelly and build history 
```
master_1  | Caused by: javax.servlet.ServletException: org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-1.643.jar!/hudson/widgets/BuildHistoryWidget/entries.jelly:31:38: <st:include> java.lang.StackOverflowError
master_1  | 	at org.kohsuke.stapler.jelly.JellyRequestDispatcher.forward(JellyRequestDispatcher.java:60)
master_1  | 	at jenkins.model.ParameterizedJobMixIn.doBuild(ParameterizedJobMixIn.java:184)
master_1  | 	at hudson.model.AbstractProject.doBuild(AbstractProject.java:1752)
master_1  | 	... 79 more
master_1  | Caused by: org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-1.643.jar!/hudson/widgets/BuildHistoryWidget/entries.jelly:31:38: <st:include> java.lang.StackOverflowError
master_1  | 	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:745)
master_1  | 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:289)
master_1  | 	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
master_1  | 	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
master_1  | 	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
master_1  | 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
```

**Comment by vvitayau** [comment]
jenkins-1.636 fails too ... whereas jenkins-1.628 works.

**Comment by vvitayau** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-30569 was introduced in https://github.com/jenkinsci/jenkins/compare/jenkins-1.632...jenkins-1.633

**Comment by vvitayau** [comment]
Culprit appears to be https://github.com/jenkinsci/jenkins/blob/078d3c7c4b5ffc5eae2f8c300a681bc340dfec60/core/src/main/resources/hudson/widgets/BuildHistoryWidget/entries.jelly#L31
```
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler">
  <st:include page="entries.jelly" />
</j:jelly>
```

**Comment by vvitayau** [comment]
Bingo

**Comment by vvitayau** [comment]
Reopen this issue ticket ... 

Hi @suryagaddipati 

Can you refactor to take advantage of the inheritance engine by correcting  [DotCi BranchHistoryWidget](https://github.com/groupon/DotCi/tree/1f06828c74d57d9962632ed0675274da3f467b20/src/main/resources/com/groupon/jenkins/branchhistory/BranchHistoryWidget) to BuildHistoryWidget as mentioned in https://github.com/jenkinsci/jenkins/pull/1966

**Comment by tfennelly** [comment]
@vvitayau ooops ... I need to look at this and figure out why ye are seeing this SO error. I haven't heard any other reports of this.

**Comment by suryagaddipati** [comment]
@tfennelly @vvitayau this was an issue in DotCi. That has been fixed with this commit https://github.com/groupon/DotCi/commit/0ddd6a600018a11943086a6a4562fcf8e4ce0f29

**Comment by vvitayau** [comment]
About to cut new (DotCi-2.28.0 release for above patch](https://github.com/groupon/DotCi/compare/DotCi-2.27.3...DotCi-2.28.0
